name: Lint and test code

on: [push]

jobs:
  runtests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        python -m pip install -r requirements-dev.txt
    - name: Analysing the code with pylint
      run: |
        pylint src/RequirementsLibrary
        pylint tests
    - name: Analysing the code with mypy
      run: |
        mypy src/RequirementsLibrary
        mypy --namespace-packages tests
    - name: Analysing the code with flake8
      run: |
        flake8 src/RequirementsLibrary
        flake8 tests
    - name: Analysing the code with black
      run: |
        black --line-length 100 --check src/RequirementsLibrary
        black --line-length 100 --check tests
    - name: Lint markdown files
      run: |
        pymarkdown scan README.md CHANGELOG.md
    - name: Run unit tests with pytest
      run: |
        pytest
    - name: Run acceptance tests with Robot Framework
      run: |
        robot atest
